# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.StartBtn.setGeometry(QtCore.QRect(20, 170, 181, 121))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.StartBtn.setFont(font)
        self.StartBtn.setObjectName("StartBtn")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(22, 30, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 30, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.GraphBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GraphBtn.setGeometry(QtCore.QRect(20, 300, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.GraphBtn.setFont(font)
        self.GraphBtn.setObjectName("GraphBtn")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 130, 541, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../Images/632470_screenshots_20191022113843_1.jpg"))
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 100, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sensitive Photographer"))
        self.StartBtn.setText(_translate("MainWindow", "Запуск"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "COM-порт"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Название"))
        self.GraphBtn.setText(_translate("MainWindow", "График"))
        self.comboBox.setPlaceholderText(_translate("MainWindow", "Микроскоп"))
