# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.StartBtn.setGeometry(QtCore.QRect(20, 170, 181, 121))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.StartBtn.setFont(font)
        self.StartBtn.setObjectName("StartBtn")
        self.PortLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.PortLineEdit.setGeometry(QtCore.QRect(22, 30, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PortLineEdit.setFont(font)
        self.PortLineEdit.setInputMask("")
        self.PortLineEdit.setText("")
        self.PortLineEdit.setObjectName("PortLineEdit")
        self.NameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NameLineEdit.setGeometry(QtCore.QRect(240, 30, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.NameLineEdit.setFont(font)
        self.NameLineEdit.setObjectName("NameLineEdit")
        self.GraphBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GraphBtn.setGeometry(QtCore.QRect(20, 300, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.GraphBtn.setFont(font)
        self.GraphBtn.setObjectName("GraphBtn")
        self.PhotoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.PhotoLabel.setGeometry(QtCore.QRect(220, 130, 541, 401))
        self.PhotoLabel.setText("")
        self.PhotoLabel.setPixmap(QtGui.QPixmap("../../../../Images/632470_screenshots_20191022113843_1.jpg"))
        self.PhotoLabel.setWordWrap(False)
        self.PhotoLabel.setOpenExternalLinks(False)
        self.PhotoLabel.setObjectName("PhotoLabel")
        self.CameraComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.CameraComboBox.setGeometry(QtCore.QRect(20, 100, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CameraComboBox.setFont(font)
        self.CameraComboBox.setObjectName("CameraComboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sensitive Photographer"))
        self.StartBtn.setText(_translate("MainWindow", "Запуск"))
        self.PortLineEdit.setPlaceholderText(_translate("MainWindow", "COM-порт"))
        self.NameLineEdit.setPlaceholderText(_translate("MainWindow", "Название"))
        self.GraphBtn.setText(_translate("MainWindow", "График"))
        self.CameraComboBox.setPlaceholderText(_translate("MainWindow", "Микроскоп"))
